### ISSUE TITLE
add support for python3-pip dependency

### ISSUE THREAD

**Issue by sami-shakir** [UdelaRInterior/ansible-role-proxmox-create-kvm#17]
Hey, running this role on my proxmox instance, fails at the dependencies because it's specifying python-pip, when my apt repo has python3-pip

https://github.com/UdelaRInterior/ansible-role-proxmox-create-kvm/blob/2cc6fb2e46774187640b00493e9843b6be5ccdaa/tasks/dependencies.yml#L6

**Comment by santiagomr** [comment]
Thanks @sami-shakir for report this failure.

This issue had already been [resolved in the sibling role](https://github.com/UdelaRInterior/ansible-role-proxmox-create-lxc/pull/19) but not here. Now it is in both.
