### ISSUE TITLE
[FEATURE]don't use the api_password when token and secret are used

### ISSUE THREAD

**Issue by flotho** [UdelaRInterior/ansible-role-proxmox-create-kvm#21]
Hi,

Great thanks for your awesome work. I was really missing this kind of role.
I would like to report the fact that I wasn't able to use user/token/secret without password . If api_password is not set the connexion to the PVE is failing. Yet commenting this https://github.com/UdelaRInterior/ansible-role-proxmox-create-kvm/blob/master/tasks/create_kvm.yml#L9 help to make the playbook successfull.

**Comment by ulvida** [comment]
> ... I wasn't able to use user/token/secret without password
We had the same limitation, but we didn't look further and just use password. 

It's great you did it!

**Comment by flotho** [comment]
https://git.interior.edu.uy/cielito/proxmox/-/merge_requests/1

**Comment by ulvida** [comment]
> https://git.interior.edu.uy/cielito/proxmox/-/merge_requests/1

For archives: the MR let to [cielito.proxmox collection](https://galaxy.ansible.com/cielito/proxmox), version [v1.2.0](https://git.interior.edu.uy/cielito/proxmox/-/tags/v1.2.0),
